[package]
name = "bevy_doryen"
version = "0.1.0"
authors = ["Tomasz Sterna <tomek@sterna.link>"]
edition = "2018"

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", default-features = false }
doryen-rs = { git = "https://github.com/jice-nospam/doryen-rs.git" }
log = "0.4"
